name: Pull code, rebuild files and restart pm2 processes

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Rebild Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd postitt.io
            git pull
            npm i
            npx tsc
            npm run build
            pm2 restart server client
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
